name: Strep_Phylogenetics
channels:
  - bioconda
    #  - conda-forge
dependencies:
  - r-traminer
        #- r-tidyverse
    #- r-base
    #- r-base=4.1.1
    #- r-essentials
    #  - r-TraMineR
    #- bioconductor-ggtree=3.0.4
    #- bioconductor-ggtree
    #  - snakemake-minimal >=5.24.1

