name: R-test
channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake-minimal >=5.24.1
#  - mawk 
  - samtools 
  - bowtie2
  - pandas
#  - python
  - python=3.8
  - pysam
  - openjdk
  - pip
  - pip:
    - metadmg[all]
  - r-base=4.1.0
