#sampledata: data/sample_info/topmap_meta.tsv
#sampledata: data/sample_info/ref_and_mags.tsv
#sampledata: data/sample_info/ref_MAG_only.tsv
#sampledata: data/sample_info/ref_MAGnew.tsv
#sampledata: data/sample_info/phylo_mag.tsv
#sampledata: data/sample_info/mag_phylo_genus.tsv
sampledata: data/sample_info/mag_phylo_biggenus.tsv
#ref_dir: ../Strep_mapping/tables/
#prefix: strep_pangenome
#prefix: Steppe_3500BP_1300BP
#prefix: mutans
#prefix: mutans-MAG-and-REF
#prefix: mutans-v8
#prefix: mutans-v8-HQ
prefix: mag-phylo-genus4
#prefix: mutans-phylo
#prefix: newmutans-MAG-and-REF
bam_dir: ../Strep_mapping/data/mapping/bam/
tmppath: data/tmp/
binning_algo: metabat2
collection_name: metabat_col2
assembly_dir: data/read_assembly/
#krakenpath: /willerslev/users-shared/science-snm-willerslev-dsw670/projects/diseases/results/pathopipe/classify/
#krakensuffix: .diseases.krakenuniq.class.tsv.gz
